version: '3'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: medilabo
      POSTGRES_PASSWORD: medilabo
      POSTGRES_DB: medilabo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/medilabo
    ports:
      - "8081:8081"
    depends_on:
      - postgresdb

volumes:
  pgdata: